# Generated by Django 4.2.6 on 2023-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_odam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('narxi', models.IntegerField()),
                ('sort', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
