# Generated by Django 4.2.6 on 2023-10-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('title', models.TextField()),
                ('distan', models.IntegerField()),
                ('rang', models.CharField(max_length=200)),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
